apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator
  namespace: cloudflare-operator-system
spec:
  interval: 10m
  path: "./config/default"
  prune: true
  sourceRef:
    kind: GitRepository
    name: cloudflare-operator
  targetNamespace: cloudflare-operator-system
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  wait: true
  timeout: 10m