apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-operator-cluster-tunnel
  namespace: cloudflare-operator-system
spec:
  interval: 10m
  path: "./infrastructure/default/cloudflare-operator/cluster-tunnel"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cloudflare-operator
      namespace: cloudflare-operator-system
  wait: true
  timeout: 5m

