apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../../base/cert-manager/namespace.yaml
  - ../../../base/cert-manager/helm-repository.yaml
  - ../../../base/cert-manager/helm-release.yaml

